version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: dockerfile
     volumes:
        - /app/node_modules
        - .:/app
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true